[package]
name = "grf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
peroxide = { version = "0.32.1", features = ["nc"] }
rand = "0.8.5"
statrs = "0.16.0"
